---
title: "Emotional Valence EEG_ANX Somatomap"
author: "Casey Jayne"
date: "9/19/2019"
output: 
  html_document:
    df_print: paged
    toc: TRUE
---

```{r libs, include=FALSE}
require("ggplot2")
#require(GGally)
require(reshape2)
require(lme4)
require(lattice)
require(dplyr)
require(tidyverse)
require("haven")
require(lsr)
require(plyr)
require(car)
#require(fitdistrplus)
#require(multcomp)
#library(lmerTest)
library(latticeExtra)  
library(markdown)
library(knitr)
require(lubridate)
library(glue)
library(readr)
```

```{r dataimport, include=FALSE}
##Import Data
inputdir='/Users/casey/Desktop/EEG_ANX/data/source/emoval'
files=list.files(path='/Users/casey/Desktop/EEG_ANX/data/source/emoval',
                 pattern="*somatomap_NOheader(.*)csv$", recursive = T, full.names = TRUE)
emolist=lapply(files, read.csv)
emodf=do.call(rbind, emolist)
str(emodf)
outputdir='/Users/casey/Desktop/EEG_ANX/data/derivatives/emoval'
numsubs=4 #total number subjects
numses=1 #total number of sessions

##fix labels ###########DATASETSPECIFIC###############
emodf$Sub=emodf$Participant.Name
emodf$Sub=as.character(emodf$Sub) #make sure not a factor in order to change w/o NAs
emodf$Sub[emodf$Sub=="sub-1-1"]="0401"
emodf$Sub[emodf$Sub=="sub-4041"]="4041"
emodf$Sub[emodf$Sub=="sub-6033"]="6033"
emodf$Sub[emodf$Sub=="sub-6037"]="6037"

#add column for group
emodf$group= rep("temp", length(emodf$Sub))
emodf$group=ifelse(emodf$Sub=="4041", "anx", 
                   ifelse(emodf$Sub=="0401", "anx", 
                          ifelse(emodf$Sub=="6033", "con",
                                 ifelse(emodf$Sub=="6037", "con", NA))))

#add column for task
emodf$Task=rep("somatomap", length(emodf$Sub))

#subset, select, and factor relevant portions
emodf=subset(emodf, select=c(Sub, group, Task, Video.Time, Valence))
emodf=within(emodf, {
  Sub=factor(Sub)
  group=factor(group)
  Task=factor(Task)
  Valence=as.numeric(as.character(Valence))
  #Valence=as.numeric(levels(Valence))[Valence]
  #Video.Time=as.numeric(as.character(Video.Time))
  #because not saved as NA, need to convert from 
  #factor to character then numeric in order to force out NAs
})
sum(is.na(emodf$Valence))
sum(!is.na(emodf$Valence))
levels(emodf$Sub)
levels(emodf$group)

####add row for MS conversion
library(lubridate)
emodf$Time=ms(emodf$Video.Time)
```

## Simple Statistics
```{r, functions, include=FALSE}
#identify functions of interest
funs=list(mean=~mean(., na.rm=TRUE), sd=~sd(., na.rm=TRUE))
```

```{r, allrespcheck, include=TRUE, echo=FALSE, warning=FALSE}
temp1= emodf %>%
  group_by(Sub, group) %>%
  summarise_at("Valence", funs)
temp2=emodf %>%
  group_by(group) %>%
  summarise_at("Valence", funs)
Alltime_Estats=bind_rows(temp1, temp2)
Alltime_Estats$Sub=ifelse(is.na(Alltime_Estats$Sub), "Overall", 
                          Alltime_Estats$Sub)
rm(temp2)
Alltime_Estats
```

## Graph, Average Valence between Groups
```{r, graphavg, include=TRUE, echo=FALSE}
#Plot
xyplot(mean~group, temp1, groups = Sub, type='p', cex=2,
       par.settings=ggplot2like(),axis=axis.grid, auto.key = TRUE, 
       main="Average Valence by Subject", ylab="Average Valence") 
```

## T Test and GLMM

Note, using a Nelder Mead Model instead of REML (standard) due to fit warnings with restricted max likelihood
```{r, allttest, include=TRUE, echo=FALSE}
t.test(mean~group, data=temp1, na.rm=TRUE,
       paired=TRUE)
cohensD(mean~group, data=temp1)

summary(lmer(Valence~group+(1+group|Sub), data=emodf, REML=FALSE, control=lmerControl(optimizer="Nelder_Mead")))
```

